### ISSUE TITLE
[BUG] example code for WordChunker is not working

### ISSUE THREAD

**Issue by mozz85** [bhavnicksm/chonkie#67]
**Describe the bug**
1. argument "mode" for WordChunker is not implemented
2. something goes wrong when I use the `tokenizer = AutoTikTokenizer.from_pretrained("gpt2")`
you can see the error detail in the **Additional context**

**To Reproduce**
```
def format_text4(input_text):
    tokenizer = AutoTikTokenizer.from_pretrained("gpt2")

    chunker = WordChunker(
        tokenizer=tokenizer,
        chunk_size=512,
        chunk_overlap=128
        # mode="advanced"
    )
    
    # split text into chunks
    chunks = chunker.chunk(input_text)
    
    formatted_text = [chunk.text for chunk in chunks]
    
    return formatted_text

format_text4('this is a test'):
```

**Additional context**
```
(SentenceBD) E:\develop\python_projects\Subtitle_Adjustment_Tool>D:/developTools/anaconda3_531/envs/SentenceBD/python.exe e:/develop/python_projects/Subtitle_Adjustment_Tool/test_chonkie_semantic_chunker.py
Fetching 5 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<?, ?it/s]
thread '<unnamed>' panicked at src\lib.rs:82:26:
no entry found for key
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src\lib.rs:82:26:
no entry found for key
thread '<unnamed>' panicked at src\lib.rs:82:26:
no entry found for key
thread '<unnamed>' panicked at src\lib.rs:82:26:
no entry found for key
thread '<unnamed>' panicked at src\lib.rs:82:26:
no entry found for key
thread '<unnamed>' panicked at src\lib.rs:82:26:
no entry found for key
thread '<unnamed>' panicked at src\lib.rs:82:26:
no entry found for key
Traceback (most recent call last):
  File "e:\develop\python_projects\Subtitle_Adjustment_Tool\test_chonkie_semantic_chunker.py", line 100, in <module>
    output_text = format_text4(input_text)
  File "e:\develop\python_projects\Subtitle_Adjustment_Tool\test_chonkie_semantic_chunker.py", line 71, in format_text4
    chunks = chunker.chunk(input_text)
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\site-packages\chonkie\chunker\word.py", line 99, in chunk
    lengths = self._get_word_list_token_counts(words)
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\site-packages\chonkie\chunker\word.py", line 83, in _get_word_list_token_counts
    encodings = self._encode_batch(words)
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\site-packages\chonkie\chunker\base.py", line 138, in _encode_batch
    return self.tokenizer.encode_batch(texts)
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\site-packages\tiktoken\core.py", line 173, in encode_batch
    return list(e.map(encoder, text))
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\developTools\anaconda3_531\envs\SentenceBD\lib\site-packages\tiktoken\core.py", line 120, in encode
    return self._core_bpe.encode(text, allowed_special)
pyo3_runtime.PanicException: no entry found for key
```

**Comment by bhavnicksm** [comment]
Hey @mozz85!

Thanks for opening an issue! 😊

Regarding your issues, respectively: 

1. I removed the mode feature to make it default to the best mode usage, but the docs have probably missed that part out. I'll update the docs as well. Thanks for pointing this out!
2. I'm unable to replicate the same issue as you are seeing, even though I am running the same code. Here's an image of me running it on colab, which seems to work? 

<img width="779" alt="Screenshot 2024-11-25 at 9 04 42 PM" src="https://github.com/user-attachments/assets/b7134d0b-f019-4078-bf70-42c1caa7a985">

Is this what you were trying? Could you send me a reproduction of the issue in a colab link if possible...? I would be able to fix the issue for you a lot faster that ways.

Thanks!

**Comment by bhavnicksm** [comment]
@mozz85, 

I think you might be facing this challenge due to a combination of using Windows + AutoTikTokenizer. AutoTikTokenizer has an open issue with windows that's being worked on at the moment. Could you maybe try the same with a `Tiktoken` tokenizer or a `Tokenizers` tokenizer. I think you wouldn't face that issue, if you are on windows with them. 

Thanks!

**Comment by mozz85** [comment]
It worked!! using the Tiktoken tokenizer instead of the AutoTikTokenizer.
